In [2]:
#Produto escalar 

import numpy as np 



#matrix a

a = np.array([[1,2],[3,4]])

print("matrix a dimension ", a.shape)



#matrix b

b = np.array([[5,6,7],[8,9, 10]]) 

print("matrix b dimension ", b.shape)



#matrix c = a.b

c = np.dot(a,b)

print("dot product of a and b: ", c)

print("matrix c dimension ", c.shape)



matrix a dimension  (2, 2)
matrix b dimension  (2, 3)
dot product of a and b:  [[21 24 27]
 [47 54 61]]
matrix c dimension  (2, 3)


In [3]:
# código para produto element-wise em Python

import numpy as np 



#matrix a

a = np.array([[1,2],[3,4]])

print("matrix a dimension ", a.shape)



#matrix b

b = np.array([[5,6],[8,9]]) 

print("matrix b dimension ", b.shape)



#matrix c = a * b

c = np.multiply(a,b)

print("element wise product of matrices a and b: ", c)

print("matrix c dimension ", c.shape)


matrix a dimension  (2, 2)
matrix b dimension  (2, 2)
element wise product of matrices a and b:  [[ 5 12]
 [24 36]]
matrix c dimension  (2, 2)


In [ ]:
# Multiplicação de uma matriz e um vetor linha

a = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])

b = np.array([1, 2, 3])

c = a * b

print(c)


In [ ]:
#Adição de uma matriz e um escalar

a = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])

b = 1

c = a + b

print(c)


In [4]:

# Chamada de função a nível de elemento

def exp(x, n):

  return x ** n



a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(exp(a, 2))


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
